# Dependencies
markdown:         redcarpet
highlighter:      pygments

# removed permalink (cant be in folder)

# Setup
title:            Aditya Anikode's Website
tagline:          'My very own website'
description:      'Welcome to my website! Please feel free to view some of the projects I have done, take look at my portfolio, and check out all the things I find cool!'
url:              http://me.adityaanikode.com
baseurl:          /

author:
  name:           'My email: '
  url:            adityaanikode@gmail.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/aaniko123/adityaanikode.com

# Featured posts for home page (specify post titles)
featured_posts:
  - "Fredrikstad"
  - "Oslo"
  - "Iceland"
  - "Japan"
  - "Colombia"
